openapi: 3.1.0
x-stoplight:
  id: i9mp04xl94sy9
info:
  title: portmone-direct
  version: '1.0'
  description: ''
  summary: portmone direct api
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    post:
      summary: 'api'
      x-microcks-dispatcher: URI_PARAMS
      x-microcks-dispatcherRules: method
      operationId: post-api
      parameters:
        - examples:
            example1:
              value: example1
            example2:
              value: example2
          name: method
          schema:
            type: string
          in: query
          required: true
      responses:
        '200':
          description: ''
          content:
            application/xml:
              examples:
                example1:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="Код помилки">Опис помилки 123</error>
                    </rsp>
                example2:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="Код помилки">456789</error>
                    </rsp>
