openapi: 3.1.0
x-stoplight:
  id: i9mp04xl94sy9
info:
  title: portmone-direct
  version: '1.0'
  description: ''
  summary: portmone direct api
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    parameters: []
    post:
      summary: ''
      operationId: post-api
      responses:
        '200':
          description: ''
          content:
            application/xml:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="Код помилки">Опис помилки 123</error>
                    </rsp>
                example-2:
                  value: |-
                    <?xml version="1.0" encoding="utf-8"?>
                    <rsp status="fail">
                        <error code="Код помилки">456789</error>
                    </rsp>
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/x-www-form-urlencoded
components:
  schemas: {}

